### ISSUE TITLE
luis list userazureaccounts -> client.azureAccounts.getUserLUISAccounts is not a function

### ISSUE THREAD

**Issue by BasSmuldersCZ** [microsoft/botbuilder-tools#1220]
## Tool
Name: LUIS
Version: 2.6.0
OS: Windows 10

## Describe the bug
After update to 2.6.0 i get error "client.azureAccounts.getUserLUISAccounts is not a function"
when calling luis list userazureaccounts

## To Reproduce
Run luis list userazureaccounts with a given authorkey, armToken, region and applicationId

## Expected behavior
Return an account
## Additional context

[bug]

**Comment by BasSmuldersCZ** [comment]
Caused by commit 205736908fd382f3480a2d7a7f43db5653353341

**Comment by sgellock** [comment]
@chrimc62 since your commit created the fun here, can you work on fixing this for me?
